version: "2.4"
# The server profiles used in this example are intended for use with edge versions of the product image only.

#-------------------------------------------------------------------------------------
#- Ping Identity Simple Stack integrated demo
#-
#-     login  console            app                console           rest    ldaps
#-     9031   9999               6443                 8443            1443    1636
#-      |      |                  |                    |               |       |
#-   +---------------+    +---------------+    +---------------+    +---------------+
#-   | PingFederate  |    | PingDelegator |    |PingDataConsole|    | PingDirectory |
#-   +---------------+    +---------------+    +---------------+    +---------------+
#-
#-  PingFederate Console                         PingDataConsole (PingDirectory)
#-  --------------------                         -------------------------------
#-  https://localhost:9999/pingfederate/app      https://localhost:8443
#-    Username: administrator                        Server: pingdirectory:1636
#-    Password: 2FederateM0re                      Username: administrator
#-                                                 Password: 2FederateM0re
#-
#-  PingDelegator App
#-  -----------------
#-  https://localhost:6443
#-    Username: administrator
#-    Password: 2FederateM0re
#-
#- NOTE: If you receive an error after pingdelegator login: 'You could not be authenticated'
#-       some browsers (i.e. Firefox) may require you to accept cert on each port.
#-       You should be able to goto https://localhost:1443 and accept the cert to continue.
#-------------------------------------------------------------------------------------

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:1389 -t 900 -- entrypoint.sh start-server
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
    environment:
#      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
#      - SERVER_PROFILE_PATH=baseline/pingfederate
      - VERBOSE=false
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ${HOME}/.pingidentity/devops
      - settings.env
      - pf.env
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
#      - pingfederate-out:/opt/out
      - ./local_profiles/pingfederate:/opt/in
      - ./licenses/pingfederate.lic:/opt/in/instance/server/default/conf/pingfederate.lic
      - ./local_profiles/studentauth:/opt/in/instance/server/default/deploy/studentauth

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
#    environment:
#      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
#      - SERVER_PROFILE_PATH=baseline/pingdirectory
    env_file:
      - ${HOME}/.pingidentity/devops
      - settings.env
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1636:1636"
      - "1443:1443"
      - "1389:1389"
    networks:
      - pingnet
    volumes:
      - pingdirectory-out:/opt/out
      - ./local_profiles/pingdirectory:/opt/in
      - ./licenses/PingDirectory.lic:/opt/in/pd.profile/server-root/pre-setup/PingDirectory.lic

  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - "8443:8443"
    networks:
      - pingnet

  pingdelegator:
    image: pingidentity/pingdelegator:edge
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
    environment:
      - PD_ENGINE_PUBLIC_PORT=1443
      - PF_ENGINE_PUBLIC_PORT=3000
#      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
#      - SERVER_PROFILE_PATH=baseline/pingdelegator
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "6443:6443"
    networks:
      - pingnet
    volumes:
      - ./local_profiles/pingdelegator:/opt/in

  httpd:
    image: httpd:latest
    ports:
      - "3000:443"
      - "443:443"
    networks:
      - pingnet
    volumes:
      - ./local_profiles/studentauth/html:/usr/local/apache2/htdocs/studentauth
      - ./local_profiles/studentauth/conf:/usr/local/apache2/conf

networks:
    pingnet:

volumes:
  pingfederate-out:
  pingdirectory-out:
